name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install frontend dependencies
        run: npm ci
      - name: frontend tests
        run: CI=true npm test -- --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
         command: npx cypress run
         start: npm start
         wait-on: http://localhost:3000
      - name: run eslint
        run: npx eslint --fix --ext .js,.jsx .
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        
